/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.util.Date;

/**
 *
 * @author Pessoa
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cadastroDialog = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        painelCadastro = new javax.swing.JPanel();
        prenomeLabel = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        sobrenomeLabel = new javax.swing.JLabel();
        dataDeNascimentoLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        paisNascimentoLabel = new javax.swing.JLabel();
        estadoCivilLabel = new javax.swing.JLabel();
        telefoneAlternativoLabel = new javax.swing.JLabel();
        emailPessoalLabel = new javax.swing.JLabel();
        emailComercialLabel = new javax.swing.JLabel();
        emailAlternativoLabel = new javax.swing.JLabel();
        matriculaLabel = new javax.swing.JLabel();
        regimeEmpregoLabel = new javax.swing.JLabel();
        regimeRemuneracaoLabel = new javax.swing.JLabel();
        centroCustoLabel = new javax.swing.JLabel();
        unidadeLabel = new javax.swing.JLabel();
        departamentoLabel = new javax.swing.JLabel();
        cargaHorariaDiariaLabel = new javax.swing.JLabel();
        cargaHorariaSemanalLabel = new javax.swing.JLabel();
        cargaHorariaQuinzenalLabel = new javax.swing.JLabel();
        cargaHorariaMensalLabel = new javax.swing.JLabel();
        remuneracaoBasicaLabel = new javax.swing.JLabel();
        remuneracaoComplementarLabel = new javax.swing.JLabel();
        telefoneResidencialLabel = new javax.swing.JLabel();
        telefoneComercialLabel = new javax.swing.JLabel();
        remuneracaoAdicionalLabel = new javax.swing.JLabel();
        remuneracaoGratificadaLabel = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        sobrenomeTextField = new javax.swing.JTextField();
        municipioDeNascimentoTextField = new javax.swing.JTextField();
        ufComboBox = new javax.swing.JComboBox();
        paisNascimentoTextField = new javax.swing.JTextField();
        estadoCivilComboBox = new javax.swing.JComboBox();
        telefoneResidencialFormattedTextField = new javax.swing.JFormattedTextField();
        telefoneComercialFormattedTextField = new javax.swing.JFormattedTextField();
        telefoneAlternativoFormattedTextField = new javax.swing.JFormattedTextField();
        emailPessoalTextField = new javax.swing.JTextField();
        emailComercialTextField = new javax.swing.JTextField();
        emailAlternativoTextField = new javax.swing.JTextField();
        regimeEmpregoComboBox = new javax.swing.JComboBox();
        regimeRemuneracaoComboBox = new javax.swing.JComboBox();
        remuneracaoBasicaTextField = new javax.swing.JTextField();
        remuneracaoComplementarTextField = new javax.swing.JTextField();
        remuneracaoAdicionalTextField = new javax.swing.JTextField();
        remuneracaoGratificadaTextField = new javax.swing.JTextField();
        titulacaoMaximaLabel = new javax.swing.JLabel();
        titulacaoMaximaTextField = new javax.swing.JTextField();
        matriculaFormattedTextField = new javax.swing.JFormattedTextField();
        preNomeComboBox = new javax.swing.JComboBox();
        centroCustoComboBox = new javax.swing.JComboBox();
        cargaHorariaDiariaTextField = new javax.swing.JTextField();
        cargaHorariaSemanalTextField = new javax.swing.JTextField();
        cargaHorariaQuinzenalTextField = new javax.swing.JTextField();
        cargaHorariaMensalTextField = new javax.swing.JTextField();
        diasComboBox = new javax.swing.JComboBox();
        mesComboBox = new javax.swing.JComboBox();
        anoComboBox = new javax.swing.JComboBox();
        unidadeTextField = new javax.swing.JTextField();
        departamentoTextField = new javax.swing.JTextField();
        finalizarCadastroBotao = new javax.swing.JButton();
        tipoLogradouroTextField = new javax.swing.JTextField();
        codigoLogradouroTextField = new javax.swing.JTextField();
        descricaoLogradouroTextField = new javax.swing.JTextField();
        complementoLogradouroTextField = new javax.swing.JTextField();
        numeroTextField = new javax.swing.JTextField();
        quadraTextField = new javax.swing.JTextField();
        loteTextField = new javax.swing.JTextField();
        bairroTextField = new javax.swing.JTextField();
        municipioTextField = new javax.swing.JTextField();
        unidadeFederacaoTextField = new javax.swing.JTextField();
        paisTextField = new javax.swing.JTextField();
        referenciaTextField = new javax.swing.JTextField();
        tipoDeLogradouroLabel = new javax.swing.JLabel();
        codigoLogradouroLabel = new javax.swing.JLabel();
        descricaoLogradouroLabel = new javax.swing.JLabel();
        complementoLogradouroLabel = new javax.swing.JLabel();
        numeroLabel = new javax.swing.JLabel();
        quadraLabel = new javax.swing.JLabel();
        loteLabel = new javax.swing.JLabel();
        bairroLabel = new javax.swing.JLabel();
        municipioLabel = new javax.swing.JLabel();
        unidadeFederacaoLabel = new javax.swing.JLabel();
        paisLabel = new javax.swing.JLabel();
        referenciaLabel = new javax.swing.JLabel();
        fundoPainel = new javax.swing.JPanel();
        barraSuperiorPainel = new javax.swing.JPanel();
        botaoCadastrar = new javax.swing.JButton();
        botaoPesquisar = new javax.swing.JButton();
        barraDePesquisaPainel = new javax.swing.JPanel();
        campoPesquisa = new javax.swing.JTextField();
        pesquisaPorRegex = new javax.swing.JTextField();
        iniciarPesquisa = new javax.swing.JButton();
        tiposDePesquisa = new javax.swing.JComboBox();
        areaDeResultadosPainel = new javax.swing.JPanel();
        jScrollBar1 = new javax.swing.JScrollBar();
        abaInformacoesPanel = new javax.swing.JPanel();
        expandirResultadoButton = new javax.swing.JButton();
        informacoesLabel = new javax.swing.JLabel();
        excluirResultadoButton = new javax.swing.JButton();
        levantamentoPanel = new javax.swing.JPanel();
        quantidadeMatchesLabel = new javax.swing.JLabel();
        quantidadeTotalLabel = new javax.swing.JLabel();
        quantidadeMatchesResultadoLabel = new javax.swing.JLabel();
        quantidadeTotalResultadoLabel = new javax.swing.JLabel();

        cadastroDialog.setTitle("Cadastro");
        cadastroDialog.setBackground(new java.awt.Color(255, 255, 255));
        cadastroDialog.setBounds(fundoPainel.getVisibleRect());
        cadastroDialog.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cadastroDialog.setMinimumSize(new java.awt.Dimension(1191, 560));

        painelCadastro.setBackground(new java.awt.Color(255, 255, 255));

        prenomeLabel.setText(" Pré Nome:");

        nomeLabel.setText("Nome:");

        sobrenomeLabel.setText("Sobrenome:");

        dataDeNascimentoLabel.setText("Data de Nascimento:");

        jLabel5.setText(" Municício de Nascimento:");

        jLabel6.setText("UF");

        paisNascimentoLabel.setText("País");

        estadoCivilLabel.setText("Estado Civil");

        telefoneAlternativoLabel.setText("Alternativo:");

        emailPessoalLabel.setText(" E-mail Pessoal:");

        emailComercialLabel.setText("Comercial:");

        emailAlternativoLabel.setText("Alternativo:");

        matriculaLabel.setText(" Matrícula:");

        regimeEmpregoLabel.setText("Regime Emprego:");

        regimeRemuneracaoLabel.setText("Regime Remuneração:");

        centroCustoLabel.setText("Centro Custo:");

        unidadeLabel.setText(" Unidade: ");

        departamentoLabel.setText("Departamento:");

        cargaHorariaDiariaLabel.setText(" Carga Horária Diária:");

        cargaHorariaSemanalLabel.setText("Semanal:");

        cargaHorariaQuinzenalLabel.setText("Quinzenal:");

        cargaHorariaMensalLabel.setText("Mensal:");

        remuneracaoBasicaLabel.setText(" Remuneração Básica:");

        remuneracaoComplementarLabel.setText("Remuneração Complementar:");

        telefoneResidencialLabel.setText(" Telefone Residencial:");

        telefoneComercialLabel.setText("Comercial:");

        remuneracaoAdicionalLabel.setText("Remuneração Adicional:");

        remuneracaoGratificadaLabel.setText("Remuneração Gratificada:");

        nomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextFieldActionPerformed(evt);
            }
        });

        ufComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Acre (AC)", "Alagoas (AL)", "Amapá (AP)", "Amazonas (AM)", "Bahia (BA)", "Ceará (CE)", "Distrito Federal (DF)", "Espírito Santo (ES)", "Goiás (GO)", "Maranhão (MA)", "Mato Grosso (MT)", "Mato Grosso do Sul (MS)", "Minas Gerais (MG)", "Pará (PA) ", "Paraíba (PB)", "Paraná (PR)", "Pernambuco (PE)", "Piauí (PI)", "Rio de Janeiro (RJ)", "Rio Grande do Norte (RN)", "Rio Grande do Sul (RS)", "Rondônia (RO)", "Roraima (RR)", "Santa Catarina (SC)", "São Paulo (SP)", "Sergipe (SE)", "Tocantins (TO)" }));

        estadoCivilComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solteiro(a)", "Casado(a)", "Conjugado(a)", "Separado(a)", "Divorciado(a)", "Viúvo(a)" }));
        estadoCivilComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoCivilComboBoxActionPerformed(evt);
            }
        });

        try {
            telefoneResidencialFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+## (##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            telefoneComercialFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+## (##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            telefoneAlternativoFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+## (##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        regimeEmpregoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00 - Desconhecido", "01 - CLT (Decreto n. 5452/1943)", "02 - Estatutário Municipal", "03 - Estatutário Estadual", "04 - Estatutário Federal", "05 - Outro" }));

        regimeRemuneracaoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00 - Desconhecido (DS)", "01 - Horista (HR)", "02 - Semanal(SM)", "03 - Quinzenal(QN)", "04 - Mensal(MS)", "05 - por Tarefa(TF)", "06 - Outro(OUT)" }));

        titulacaoMaximaLabel.setText(" Titulação Máxima:");

        try {
            matriculaFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        preNomeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Prenome", " ", "Sr.", "Sra.", "Dr.", "Dra." }));

        centroCustoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00  - Desconhecido(DS)", "01  - UFG - Goiânia (Câmpus I)(UFG-I) ", "02  - UFG - Goiânia (Câmpus II) (UFG-II)", "03  - UFG - Catalão (UFG-CAT)", "04  - UFG - Jataí (UFG-JAT)", "05  - Outro(OUT)", " " }));

        diasComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dia", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        mesComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mês", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", " " }));

        anoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ano", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929" }));

        finalizarCadastroBotao.setText("Finalizar Cadastro");
        finalizarCadastroBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarCadastroBotaoActionPerformed(evt);
            }
        });

        tipoLogradouroTextField.setText(" ");

        tipoDeLogradouroLabel.setText(" Tipo de Logradouro: ");

        codigoLogradouroLabel.setText(" Código Logradouro: ");

        descricaoLogradouroLabel.setText(" Descricao Logradouro: ");

        complementoLogradouroLabel.setText(" Complemento Logradouro: ");

        numeroLabel.setText(" Número: ");

        quadraLabel.setText(" Quadra: ");

        loteLabel.setText(" Lote: ");

        bairroLabel.setText(" Bairro: ");

        municipioLabel.setText(" Município: ");

        unidadeFederacaoLabel.setText(" Unidade Federação: ");

        paisLabel.setText(" País: ");

        referenciaLabel.setText(" Referencia: ");

        javax.swing.GroupLayout painelCadastroLayout = new javax.swing.GroupLayout(painelCadastro);
        painelCadastro.setLayout(painelCadastroLayout);
        painelCadastroLayout.setHorizontalGroup(
            painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCadastroLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(finalizarCadastroBotao)
                        .addGap(19, 19, 19))
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCadastroLayout.createSequentialGroup()
                                .addComponent(prenomeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(preNomeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sobrenomeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sobrenomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataDeNascimentoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(diasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(municipioDeNascimentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ufComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paisNascimentoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paisNascimentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estadoCivilLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(estadoCivilComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelCadastroLayout.createSequentialGroup()
                        .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(painelCadastroLayout.createSequentialGroup()
                                .addComponent(tipoDeLogradouroLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tipoLogradouroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codigoLogradouroLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(codigoLogradouroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descricaoLogradouroLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(descricaoLogradouroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(complementoLogradouroLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(complementoLogradouroTextField))
                            .addGroup(painelCadastroLayout.createSequentialGroup()
                                .addComponent(numeroLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numeroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quadraLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quadraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loteLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bairroLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bairroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(municipioLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(municipioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(unidadeFederacaoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(unidadeFederacaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paisLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(referenciaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(referenciaTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelCadastroLayout.createSequentialGroup()
                                .addComponent(titulacaoMaximaLabel)
                                .addGap(21, 21, 21)
                                .addComponent(titulacaoMaximaTextField))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelCadastroLayout.createSequentialGroup()
                                .addComponent(unidadeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(unidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelCadastroLayout.createSequentialGroup()
                                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(telefoneResidencialLabel)
                                    .addComponent(emailPessoalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelCadastroLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(emailPessoalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelCadastroLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(telefoneResidencialFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(29, 29, 29)
                                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(painelCadastroLayout.createSequentialGroup()
                                        .addGap(200, 200, 200)
                                        .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(painelCadastroLayout.createSequentialGroup()
                                                .addComponent(telefoneAlternativoLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(telefoneAlternativoFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(painelCadastroLayout.createSequentialGroup()
                                                .addComponent(emailAlternativoLabel)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(emailAlternativoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(painelCadastroLayout.createSequentialGroup()
                                        .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(emailComercialLabel)
                                            .addComponent(telefoneComercialLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(emailComercialTextField)
                                            .addComponent(telefoneComercialFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelCadastroLayout.createSequentialGroup()
                                .addComponent(matriculaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(matriculaFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(painelCadastroLayout.createSequentialGroup()
                                        .addComponent(departamentoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(departamentoTextField))
                                    .addGroup(painelCadastroLayout.createSequentialGroup()
                                        .addComponent(regimeEmpregoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(regimeEmpregoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(8, 8, 8)
                                .addComponent(regimeRemuneracaoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(regimeRemuneracaoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(centroCustoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(centroCustoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelCadastroLayout.createSequentialGroup()
                                .addComponent(remuneracaoBasicaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(remuneracaoBasicaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(remuneracaoComplementarLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(remuneracaoComplementarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(remuneracaoAdicionalLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(remuneracaoAdicionalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(remuneracaoGratificadaLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(remuneracaoGratificadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, painelCadastroLayout.createSequentialGroup()
                                .addComponent(cargaHorariaDiariaLabel)
                                .addGap(2, 2, 2)
                                .addComponent(cargaHorariaDiariaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cargaHorariaSemanalLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cargaHorariaSemanalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cargaHorariaQuinzenalLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cargaHorariaQuinzenalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cargaHorariaMensalLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cargaHorariaMensalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        painelCadastroLayout.setVerticalGroup(
            painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prenomeLabel)
                    .addComponent(nomeLabel)
                    .addComponent(sobrenomeLabel)
                    .addComponent(dataDeNascimentoLabel)
                    .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sobrenomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(preNomeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(municipioDeNascimentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(ufComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paisNascimentoLabel)
                    .addComponent(paisNascimentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estadoCivilLabel)
                    .addComponent(estadoCivilComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoLogradouroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipoDeLogradouroLabel)
                    .addComponent(codigoLogradouroLabel)
                    .addComponent(codigoLogradouroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descricaoLogradouroLabel)
                    .addComponent(descricaoLogradouroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(complementoLogradouroLabel)
                    .addComponent(complementoLogradouroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroLabel)
                    .addComponent(numeroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quadraLabel)
                    .addComponent(quadraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loteLabel)
                    .addComponent(loteTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bairroLabel)
                    .addComponent(bairroTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(municipioLabel)
                    .addComponent(municipioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unidadeFederacaoLabel)
                    .addComponent(unidadeFederacaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paisLabel)
                    .addComponent(paisTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(referenciaLabel)
                    .addComponent(referenciaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telefoneAlternativoLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(telefoneResidencialLabel)
                        .addComponent(telefoneResidencialFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(telefoneComercialLabel)
                        .addComponent(telefoneComercialFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(telefoneAlternativoFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailPessoalLabel)
                    .addComponent(emailPessoalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailComercialLabel)
                    .addComponent(emailComercialTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailAlternativoLabel)
                    .addComponent(emailAlternativoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matriculaLabel)
                    .addComponent(regimeEmpregoLabel)
                    .addComponent(regimeEmpregoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regimeRemuneracaoLabel)
                    .addComponent(regimeRemuneracaoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(centroCustoLabel)
                    .addComponent(matriculaFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(centroCustoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unidadeLabel)
                    .addComponent(departamentoLabel)
                    .addComponent(unidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departamentoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargaHorariaDiariaLabel)
                    .addComponent(cargaHorariaQuinzenalLabel)
                    .addComponent(cargaHorariaMensalLabel)
                    .addComponent(cargaHorariaDiariaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargaHorariaSemanalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargaHorariaQuinzenalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargaHorariaMensalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cargaHorariaSemanalLabel))
                .addGap(13, 13, 13)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remuneracaoBasicaLabel)
                    .addComponent(remuneracaoBasicaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remuneracaoComplementarLabel)
                    .addComponent(remuneracaoComplementarTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remuneracaoAdicionalLabel)
                    .addComponent(remuneracaoAdicionalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remuneracaoGratificadaLabel)
                    .addComponent(remuneracaoGratificadaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulacaoMaximaLabel)
                    .addComponent(titulacaoMaximaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(finalizarCadastroBotao)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(painelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout cadastroDialogLayout = new javax.swing.GroupLayout(cadastroDialog.getContentPane());
        cadastroDialog.getContentPane().setLayout(cadastroDialogLayout);
        cadastroDialogLayout.setHorizontalGroup(
            cadastroDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1162, Short.MAX_VALUE)
            .addGroup(cadastroDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroDialogLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        cadastroDialogLayout.setVerticalGroup(
            cadastroDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
            .addGroup(cadastroDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroDialogLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Roboto Thin", 0, 10)); // NOI18N

        fundoPainel.setBackground(new java.awt.Color(255, 255, 255));

        botaoCadastrar.setText("CADASTRAR");
        botaoCadastrar.setToolTipText("Aba para cadastro ");
        botaoCadastrar.setBorderPainted(false);
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        botaoPesquisar.setText("PESQUISAR");
        botaoPesquisar.setBorderPainted(false);
        botaoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout barraSuperiorPainelLayout = new javax.swing.GroupLayout(barraSuperiorPainel);
        barraSuperiorPainel.setLayout(barraSuperiorPainelLayout);
        barraSuperiorPainelLayout.setHorizontalGroup(
            barraSuperiorPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraSuperiorPainelLayout.createSequentialGroup()
                .addComponent(botaoCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoPesquisar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        barraSuperiorPainelLayout.setVerticalGroup(
            barraSuperiorPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraSuperiorPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(botaoCadastrar)
                .addComponent(botaoPesquisar))
        );

        campoPesquisa.setText("KEYWORD");

        pesquisaPorRegex.setText("REGEX");
        pesquisaPorRegex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaPorRegexActionPerformed(evt);
            }
        });

        iniciarPesquisa.setText("jButton1");

        tiposDePesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Formas de Pesquisa", "Código de Matrícula" }));

        javax.swing.GroupLayout barraDePesquisaPainelLayout = new javax.swing.GroupLayout(barraDePesquisaPainel);
        barraDePesquisaPainel.setLayout(barraDePesquisaPainelLayout);
        barraDePesquisaPainelLayout.setHorizontalGroup(
            barraDePesquisaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraDePesquisaPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(campoPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pesquisaPorRegex, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tiposDePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iniciarPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        barraDePesquisaPainelLayout.setVerticalGroup(
            barraDePesquisaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barraDePesquisaPainelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(barraDePesquisaPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pesquisaPorRegex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iniciarPesquisa)
                    .addComponent(tiposDePesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        abaInformacoesPanel.setBackground(new java.awt.Color(102, 255, 153));
        abaInformacoesPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));

        expandirResultadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expandirResultadoButtonActionPerformed(evt);
            }
        });

        informacoesLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        informacoesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        informacoesLabel.setText("Informações");

        excluirResultadoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirResultadoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout abaInformacoesPanelLayout = new javax.swing.GroupLayout(abaInformacoesPanel);
        abaInformacoesPanel.setLayout(abaInformacoesPanelLayout);
        abaInformacoesPanelLayout.setHorizontalGroup(
            abaInformacoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaInformacoesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(expandirResultadoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(informacoesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(excluirResultadoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        abaInformacoesPanelLayout.setVerticalGroup(
            abaInformacoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaInformacoesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaInformacoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(abaInformacoesPanelLayout.createSequentialGroup()
                        .addGroup(abaInformacoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(expandirResultadoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(informacoesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(excluirResultadoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        levantamentoPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.lightGray));

        quantidadeMatchesLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        quantidadeMatchesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quantidadeMatchesLabel.setText("Quantidade Matches");

        quantidadeTotalLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        quantidadeTotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quantidadeTotalLabel.setText("Quantidade Total");

        quantidadeMatchesResultadoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quantidadeMatchesResultadoLabel.setText("0000");

        quantidadeTotalResultadoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quantidadeTotalResultadoLabel.setText("0000");

        javax.swing.GroupLayout levantamentoPanelLayout = new javax.swing.GroupLayout(levantamentoPanel);
        levantamentoPanel.setLayout(levantamentoPanelLayout);
        levantamentoPanelLayout.setHorizontalGroup(
            levantamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(levantamentoPanelLayout.createSequentialGroup()
                .addComponent(quantidadeMatchesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quantidadeMatchesResultadoLabel)
                .addGap(10, 10, 10)
                .addComponent(quantidadeTotalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quantidadeTotalResultadoLabel)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        levantamentoPanelLayout.setVerticalGroup(
            levantamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, levantamentoPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(levantamentoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantidadeMatchesLabel)
                    .addComponent(quantidadeTotalLabel)
                    .addComponent(quantidadeMatchesResultadoLabel)
                    .addComponent(quantidadeTotalResultadoLabel)))
        );

        javax.swing.GroupLayout areaDeResultadosPainelLayout = new javax.swing.GroupLayout(areaDeResultadosPainel);
        areaDeResultadosPainel.setLayout(areaDeResultadosPainelLayout);
        areaDeResultadosPainelLayout.setHorizontalGroup(
            areaDeResultadosPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, areaDeResultadosPainelLayout.createSequentialGroup()
                .addGroup(areaDeResultadosPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(areaDeResultadosPainelLayout.createSequentialGroup()
                        .addComponent(abaInformacoesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(areaDeResultadosPainelLayout.createSequentialGroup()
                        .addComponent(levantamentoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        areaDeResultadosPainelLayout.setVerticalGroup(
            areaDeResultadosPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
            .addGroup(areaDeResultadosPainelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(abaInformacoesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(levantamentoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout fundoPainelLayout = new javax.swing.GroupLayout(fundoPainel);
        fundoPainel.setLayout(fundoPainelLayout);
        fundoPainelLayout.setHorizontalGroup(
            fundoPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barraSuperiorPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(fundoPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fundoPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fundoPainelLayout.createSequentialGroup()
                        .addComponent(areaDeResultadosPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addComponent(barraDePesquisaPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        fundoPainelLayout.setVerticalGroup(
            fundoPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fundoPainelLayout.createSequentialGroup()
                .addComponent(barraSuperiorPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraDePesquisaPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(areaDeResultadosPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fundoPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1199, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextFieldActionPerformed

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
        // TODO add your handling code here:
        cadastroDialog.pack();
        cadastroDialog.setLocationRelativeTo(null);
        cadastroDialog.setVisible(true);
        
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void botaoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoPesquisarActionPerformed

    private void pesquisaPorRegexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaPorRegexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisaPorRegexActionPerformed

    private void estadoCivilComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoCivilComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoCivilComboBoxActionPerformed

    private void finalizarCadastroBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarCadastroBotaoActionPerformed
        // TODO add your handling code here:
        
        
        String preNomeString = preNomeComboBox.getSelectedItem().toString();
        String nome = nomeTextField.getText();
        String sobrenome = sobrenomeTextField.getText();
        
        //Precisando arrumar exceções
        Date dataDeNascimentoDate;
        int diaNascimento = 0;
        int mesNascimento = 0;
        int anoNascimento = 0;
        
            try{
                diaNascimento = Integer.parseInt(diasComboBox.getSelectedItem().toString());
                
            }
            catch(NumberFormatException e){
                System.out.println("Problema");
                
            }
            
            try{
                mesNascimento = Integer.parseInt(mesComboBox.getSelectedItem().toString());
                
            }catch(NumberFormatException e){
                System.out.println("Problema");
            }
            
            try{
                anoNascimento = Integer.parseInt(anoComboBox.getSelectedItem().toString());
                
            }catch(NumberFormatException e){
                System.out.println("Problema");
            }
        
        dataDeNascimentoDate = new Date( anoNascimento, mesNascimento, diaNascimento);
        
        
        String municipioDeNascimentoString = municipioDeNascimentoTextField.getText();
        String ufString = ufComboBox.getSelectedItem().toString();
        String paisString = paisNascimentoTextField.getText();
        String estadoCivilString = estadoCivilComboBox.getSelectedItem().toString();
        
        //Criando o objeto endereço
        int tipoDeLogradouroInt = Integer.parseInt( tipoLogradouroTextField.getText());
        int codigoLogradouroInt = Integer.parseInt(codigoLogradouroTextField.getText());
        String descricaoLogradouroString = descricaoLogradouroTextField.getText();
        String complementoLogradouroString  =complementoLogradouroTextField.getText();
        
        String numeroString = numeroTextField.getText();
        int numeroInt;
        if(" ".equals(numeroString) | "".equals(numeroString) )
             numeroInt= 0;
        else
            numeroInt = Integer.parseInt(numeroString);
        
        String quadraString = quadraTextField.getText();
        String loteString = loteTextField.getText();
        String bairroString = bairroTextField.getText();
        
        Long municipioLong = Long.parseLong(municipioTextField.getText());
        int unidadeFederacaoInt = Integer.parseInt(unidadeFederacaoTextField.getText());
        int paisInt = Integer.parseInt(paisTextField.getText());
        
        String referenciaString = referenciaTextField.getText();
        
        Endereco enderecoEndereco = new Endereco(tipoDeLogradouroInt, codigoLogradouroInt, descricaoLogradouroString, 
                                                 complementoLogradouroString, numeroInt, quadraString, loteString, 
                                                 bairroString, municipioLong, unidadeFederacaoInt, paisInt,referenciaString );
        
        String telefoneResidencialString = telefoneResidencialFormattedTextField.getText();
        String telefoneComercialString = telefoneComercialFormattedTextField.getText();
        String telefoneAlternativoString = telefoneAlternativoFormattedTextField.getText();
        
        String emailPessoalString = emailPessoalTextField.getText();
        String emailComercialString = emailComercialTextField.getText();
        String emailAlternativoString = emailAlternativoTextField.getText();
        
        String matriculaString = matriculaFormattedTextField.getText();
        String regimeEmpregoString = regimeEmpregoComboBox.getSelectedItem().toString();
        String regimeRemuneracaoString = regimeRemuneracaoComboBox.getSelectedItem().toString();
        String centroCustoString = centroCustoComboBox.getSelectedItem().toString();
        
        String unidadeString = unidadeTextField.getText();
        String departamentoString = departamentoTextField.getText();
        
        String cargaHorariaDiariaString = cargaHorariaDiariaTextField.getText();
        String cargaHorariaSemanalString = cargaHorariaSemanalTextField.getText();
        String cargaHorariaQuinzenalString = cargaHorariaQuinzenalTextField.getText();
        String cargaHorariaMensalString = cargaHorariaMensalTextField.getText();
        
        String remuneracaoBasicaString = remuneracaoBasicaTextField.getText();
        String remuneracaoComplementarString = remuneracaoComplementarTextField.getText();
        String remuneracaoAdicionalString = remuneracaoAdicionalTextField.getText();
        String remuneracaoGratificadaString = remuneracaoGratificadaTextField.getText();
        
        String titulacaoMaximaString = titulacaoMaximaTextField.getText();
        
    }//GEN-LAST:event_finalizarCadastroBotaoActionPerformed

    private void expandirResultadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expandirResultadoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expandirResultadoButtonActionPerformed

    private void excluirResultadoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirResultadoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_excluirResultadoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel abaInformacoesPanel;
    private javax.swing.JComboBox anoComboBox;
    private javax.swing.JPanel areaDeResultadosPainel;
    private javax.swing.JLabel bairroLabel;
    private javax.swing.JTextField bairroTextField;
    private javax.swing.JPanel barraDePesquisaPainel;
    private javax.swing.JPanel barraSuperiorPainel;
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoPesquisar;
    private javax.swing.JDialog cadastroDialog;
    private javax.swing.JTextField campoPesquisa;
    private javax.swing.JLabel cargaHorariaDiariaLabel;
    private javax.swing.JTextField cargaHorariaDiariaTextField;
    private javax.swing.JLabel cargaHorariaMensalLabel;
    private javax.swing.JTextField cargaHorariaMensalTextField;
    private javax.swing.JLabel cargaHorariaQuinzenalLabel;
    private javax.swing.JTextField cargaHorariaQuinzenalTextField;
    private javax.swing.JLabel cargaHorariaSemanalLabel;
    private javax.swing.JTextField cargaHorariaSemanalTextField;
    private javax.swing.JComboBox centroCustoComboBox;
    private javax.swing.JLabel centroCustoLabel;
    private javax.swing.JLabel codigoLogradouroLabel;
    private javax.swing.JTextField codigoLogradouroTextField;
    private javax.swing.JLabel complementoLogradouroLabel;
    private javax.swing.JTextField complementoLogradouroTextField;
    private javax.swing.JLabel dataDeNascimentoLabel;
    private javax.swing.JLabel departamentoLabel;
    private javax.swing.JTextField departamentoTextField;
    private javax.swing.JLabel descricaoLogradouroLabel;
    private javax.swing.JTextField descricaoLogradouroTextField;
    private javax.swing.JComboBox diasComboBox;
    private javax.swing.JLabel emailAlternativoLabel;
    private javax.swing.JTextField emailAlternativoTextField;
    private javax.swing.JLabel emailComercialLabel;
    private javax.swing.JTextField emailComercialTextField;
    private javax.swing.JLabel emailPessoalLabel;
    private javax.swing.JTextField emailPessoalTextField;
    private javax.swing.JComboBox estadoCivilComboBox;
    private javax.swing.JLabel estadoCivilLabel;
    private javax.swing.JButton excluirResultadoButton;
    private javax.swing.JButton expandirResultadoButton;
    private javax.swing.JButton finalizarCadastroBotao;
    private javax.swing.JPanel fundoPainel;
    private javax.swing.JLabel informacoesLabel;
    private javax.swing.JButton iniciarPesquisa;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JPanel levantamentoPanel;
    private javax.swing.JLabel loteLabel;
    private javax.swing.JTextField loteTextField;
    private javax.swing.JFormattedTextField matriculaFormattedTextField;
    private javax.swing.JLabel matriculaLabel;
    private javax.swing.JComboBox mesComboBox;
    private javax.swing.JTextField municipioDeNascimentoTextField;
    private javax.swing.JLabel municipioLabel;
    private javax.swing.JTextField municipioTextField;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JLabel numeroLabel;
    private javax.swing.JTextField numeroTextField;
    private javax.swing.JPanel painelCadastro;
    private javax.swing.JLabel paisLabel;
    private javax.swing.JLabel paisNascimentoLabel;
    private javax.swing.JTextField paisNascimentoTextField;
    private javax.swing.JTextField paisTextField;
    private javax.swing.JTextField pesquisaPorRegex;
    private javax.swing.JComboBox preNomeComboBox;
    private javax.swing.JLabel prenomeLabel;
    private javax.swing.JLabel quadraLabel;
    private javax.swing.JTextField quadraTextField;
    private javax.swing.JLabel quantidadeMatchesLabel;
    private javax.swing.JLabel quantidadeMatchesResultadoLabel;
    private javax.swing.JLabel quantidadeTotalLabel;
    private javax.swing.JLabel quantidadeTotalResultadoLabel;
    private javax.swing.JLabel referenciaLabel;
    private javax.swing.JTextField referenciaTextField;
    private javax.swing.JComboBox regimeEmpregoComboBox;
    private javax.swing.JLabel regimeEmpregoLabel;
    private javax.swing.JComboBox regimeRemuneracaoComboBox;
    private javax.swing.JLabel regimeRemuneracaoLabel;
    private javax.swing.JLabel remuneracaoAdicionalLabel;
    private javax.swing.JTextField remuneracaoAdicionalTextField;
    private javax.swing.JLabel remuneracaoBasicaLabel;
    private javax.swing.JTextField remuneracaoBasicaTextField;
    private javax.swing.JLabel remuneracaoComplementarLabel;
    private javax.swing.JTextField remuneracaoComplementarTextField;
    private javax.swing.JLabel remuneracaoGratificadaLabel;
    private javax.swing.JTextField remuneracaoGratificadaTextField;
    private javax.swing.JLabel sobrenomeLabel;
    private javax.swing.JTextField sobrenomeTextField;
    private javax.swing.JFormattedTextField telefoneAlternativoFormattedTextField;
    private javax.swing.JLabel telefoneAlternativoLabel;
    private javax.swing.JFormattedTextField telefoneComercialFormattedTextField;
    private javax.swing.JLabel telefoneComercialLabel;
    private javax.swing.JFormattedTextField telefoneResidencialFormattedTextField;
    private javax.swing.JLabel telefoneResidencialLabel;
    private javax.swing.JLabel tipoDeLogradouroLabel;
    private javax.swing.JTextField tipoLogradouroTextField;
    private javax.swing.JComboBox tiposDePesquisa;
    private javax.swing.JLabel titulacaoMaximaLabel;
    private javax.swing.JTextField titulacaoMaximaTextField;
    private javax.swing.JComboBox ufComboBox;
    private javax.swing.JLabel unidadeFederacaoLabel;
    private javax.swing.JTextField unidadeFederacaoTextField;
    private javax.swing.JLabel unidadeLabel;
    private javax.swing.JTextField unidadeTextField;
    // End of variables declaration//GEN-END:variables
}
